cerad/ng2016

gulpfile.js
src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Resources/public/css/app.css
src/AppBundle/Resources/public/css/cssmenu.css
src/AppBundle/Resources/public/css/fieldset.css
src/AppBundle/Resources/public/css/reset.css

Refactored CSS to separate & begin cleanup to CSS Lint standards.

Refactored CSS to separate & begin cleanup to CSS Lint standards.

---

src/AppBundle/Action/AbstractTemplate.php
src/AppBundle/Action/GameReport/GameReportRepository.php
src/AppBundle/Action/GameReport/Update/GameReportUpdateController.php
src/AppBundle/Action/GameReport/Update/GameReportUpdateView.php
src/AppBundle/Action/Results/PoolPlay/Calculator/PointsCalculator.php
src/AppBundle/Action/Results/PoolPlay/Calculator/StandingsCalculator.php
src/AppBundle/Action/Results/PoolPlay/ResultsPoolPlayController.php
src/AppBundle/Action/Schedule/ScheduleRepository.php
src/AppBundle/DependencyInjection/AppExtension.php
src/AppBundle/Listener/KernelListener.php
src/AppBundle/Resources/config/routes/game.yml
src/AppBundle/Resources/config/routing.yml
src/AppBundle/Resources/config/services/app.yml
src/AppBundle/Resources/config/services/game.yml
src/AppBundle/Resources/config/services/results.yml
src/AppBundle/Resources/docs/gameReports.md
src/AppBundle/Resources/docs/mvc.md
src/ProjectBundle/ProjectFactory.php
tests/AppBundle/Action/GameReport/GameReportRepositoryTest.php
tests/AppBundle/Action/Results/PoolPlay/PointsCalculatorTest.php

GameReportUpdate skelton
GameReportUpdate form
Query done and form display
View infrastructure
Added posting
Refactored points calculator

Game report update functionality

---

src/AppBundle/Action/AbstractView2.php
src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/App/Welcome/WelcomeView.php
src/AppBundle/Action/App/services.yml
src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Action/Project/Person/Register/RegisterView.php
src/AppBundle/Action/Project/User/Create/UserCreateView.php
src/AppBundle/Action/Project/User/Login/UserLoginForm.php
src/AppBundle/Action/Project/User/Password/ResetRequest/PasswordResetRequestView.php
src/AppBundle/Action/Project/User/Password/ResetResponse/PasswordResetResponseView.php
src/AppBundle/Resources/public/css/app.css
src/AppBundle/Resources/public/css/bs_custom.css

- updates for consistent styling and mobile layout
- added show_results_menu toggle to welcome notes content
- restored Home menu item without show_results_menu

Enhancement #41: Update registration styling and layout

---

src/AppBundle/Action/Project/User/Authen/Provider.php
src/AppBundle/Action/Project/User/ProjectUser.php
src/AppBundle/Action/Project/User/user.md

Important: Delete var/sessions after installing.

Implement ProjectUser serializer to minimize session data storage.

---

src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingView.php
src/AppBundle/Action/Project/Person/Admin/services.yml
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php
src/AppBundle/Action/Project/User/ProjectUserRepository.php

Getting closer.  Lots of info.  Need to migrate plans and availability from 2014 for better testing.

Register Person Listing

---

package.json
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php

Also added cache-clear to package.json.

Left a debug statement in.

---

src/AppBundle/Action/App/Admin/AdminView.php

• Make Tom Bobadilla the help contact for Referee Assignment

• Remove Tom Tobin from Admin Help

---

app/config/projects/AYSONationalGames2016.yml
src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/App/services.yml
src/AppBundle/Action/Project/Migrate/ProjectMigrateCommand.php
src/AppBundle/Action/Project/Person/ProjectPerson.php
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php
src/AppBundle/Action/Project/Person/Register/RegisterController.php
src/AppBundle/Action/Project/Person/Register/RegisterTemplateEmail.php
src/AppBundle/Action/Project/Person/services.yml

Also changed 'Phone Number' label to 'Mobile Phone'.
Added concussion aware support.
Going to hold off on Florida background checking for now.

Updated registration will coach and availability

---

src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/Project/Person/Register/RegisterTemplateEmail.php
src/AppBundle/Action/Project/User/Create/UserCreateForm.php
src/AppBundle/Action/Project/User/Create/UserCreateView.php

Added Referee Hotel Discount information to HomeView
Updated "zAYSO" on UserCreateForm and UserCreateView

Updated RegisterTemplateEmail with NO notes & links

---

src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/App/services.yml
src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingView.php
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php
src/AppBundle/Action/Project/Person/Register/RegisterTemplateEmail.php
src/AppBundle/Resources/public/css/bs_custom.css

Do not understand why the background classes are not being applied to the email but I also star problems so that's okay.

Updated Home View and registration email to indicate ayso problems.

---

src/AppBundle/Action/Project/Person/ProjectPerson.php
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php
src/AppBundle/Action/Project/Person/Register/RegisterTemplateEmail.php

- Updated email template with Tom T's inputs
- Updated ProjectPersonViewDecorator with person to access certs

Feature#77-Update email with new SafeHaven content

---

src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/App/Welcome/WelcomeView.php

Updated the Welcome page message to Blue Sombrero & WooFoo volunteers to use the password reset functionality the first time they access the system.

Feature#86 generalize welcome to all volunteers

---

src/AppBundle/Action/App/Welcome/WelcomeView.php
src/AppBundle/Action/Project/Person/Register/RegisterController.php

- Update BCC on registration to  web.ng2016@gmail.com
- Remove extra <div class="container> from WelcomeView

Go Live touchups

---

app/config/security.yml
src/AppBundle/Action/App/Admin/AdminView.php
src/AppBundle/Resources/public/css/schedule.css

Feature#80 update security model

---

app/config/projects/AYSONationalGames2016.yml
src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingController.php
src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingSearchForm.php
src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingView.php
src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateController.php
src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php
src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateTest.php
src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateView.php
src/AppBundle/Action/Project/Person/Admin/routes.yml
src/AppBundle/Action/Project/Person/Admin/services.yml
src/AppBundle/Action/Project/Person/ProjectPersonViewDecorator.php
src/AppBundle/Resources/public/css/app.css
src/AppBundle/Resources/public/css/bs_custom.css

Incorporated notes from today's call.

Feature#79 update person view

---

src/AppBundle/Action/GameReport2016/Update/GameReportUpdateForm.php
src/AppBundle/Resources/public/css/bs_custom.css

- Added check for ROLE_SCORE_ADMIN to Game & Report Status
- Applied Bootstrap CSS to form for Desktop & Mobile

Enhancement#109:

---

src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php

Bug#120-Undefined_SAR_offset:

---

src/AppBundle/Action/Physical/Ayso/Load/LoadOrgsCommand.php
src/AppBundle/Action/Physical/Ayso/schema.sql
src/AppBundle/Action/Physical/Ayso/services.yml

Also added communities to the orgs (aka region) table.  Might be useful when comparing regions geographically.  Grab new database from shared drive.

Added load command for ayso regions.  

---

src/AppBundle/Action/AbstractForm.php
src/AppBundle/Action/Schedule2016/Game/ScheduleGameSearchForm.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialSearchForm.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamSearchForm.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamView.php
src/AppBundle/Resources/public/css/app.css

- Added IsAdminStyle to AbstractForm
- Add .schedule-search to app.css
- Applied class & styling to ScheduleGameSearchForm, ScheduleOfficialSearchForm and ScheduleTeamSearchForm
- Removed legend from ScheduleTeamView for consistency

Feature#118-Make_project_selector_conditional_on_role:

---

src/AppBundle/Action/AbstractExporter.php
src/AppBundle/Action/Schedule/services.yml
src/AppBundle/Action/Schedule2016/FieldMap/ScheduleFieldMapTest.php
src/AppBundle/Action/Schedule2016/Game/ScheduleGameSearchForm.php
src/AppBundle/Action/Schedule2016/Game/ScheduleGameTest.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialSearchForm.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialTest.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialView.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialViewFile.php
src/AppBundle/Action/Schedule2016/ScheduleGameTeam.php
src/AppBundle/Action/Schedule2016/ScheduleTemplate.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamSearchForm.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamTest.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamView.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamViewFile.php
src/AppBundle/Action/Schedule2016/routes.yml
src/AppBundle/Action/Schedule2016/services.yml

Rebase complete without errors.
Pull request will complete 
- Issue https://github.com/cerad/ng2016/issues/117: Add export to official schedule
- Issue https://github.com/cerad/ng2016/issues/92: Fix Export to Text on the schedule pages

Feature#92 export to text

---

src/AppBundle/Action/AbstractForm.php
src/AppBundle/Action/GameReport2016/Update/GameReportUpdateForm.php
src/AppBundle/Resources/public/css/app.css

- No bug, just invisible error messages
- Added Error rendering

Bug#129:No bug; were errors

---

src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalController.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalRoundTest.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalSearchForm.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalView.php
src/AppBundle/Action/Results2016/PoolPlay/ResultsPoolPlaySearchForm.php
src/AppBundle/Action/Results2016/ResultsFinalCalculator.php
src/AppBundle/Action/Results2016/ResultsSportsmanshipCalculator.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipController.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipSearchForm.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipTest.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipView.php
src/AppBundle/Action/Results2016/routes.yml
src/AppBundle/Action/Results2016/services.yml
src/AppBundle/Resources/public/css/app.css

Convert all Results to 2016
Fixed bug in Final Standings listing

Feature#130 update results to 2016

---

src/AppBundle/Action/Project/Person/Admin/AdminViewFilters.php
src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php

- Fix filters to include "Maybe"
- Fix "hasIssues" to include Role issues
- Fix bug in extracting from orgKey

Bug#138-fix_admin_reports

---

app/config/routing.yml
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalRoundTest.php
src/AppBundle/Action/Results2016/MedalRound/ResultsMedalRoundTest.php
src/AppBundle/Action/Results2016/PoolPlay/ResultsPoolPlayTest.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipTest.php
src/AppBundle/Action/Schedule2016/FieldMap/ScheduleFieldMapTest.php
src/AppBundle/Action/Schedule2016/Game/ScheduleGameTest.php
src/AppBundle/Action/Schedule2016/Official/ScheduleOfficialTest.php
src/AppBundle/Action/Schedule2016/Team/ScheduleTeamTest.php

- updated routing to rename /schedule2016 to /schedule
- updated routing to rename /results2016 to /results
- Ran all tests under /src...all passed
- Ran through all menu items and verified all worked

Feature148-remove_2016_from_paths

---

src/AppBundle/Action/GameOfficial/AssignByAssignor/AssignorController.php
src/AppBundle/Action/GameOfficial/AssignByAssignor/AssignorFinder.php
src/AppBundle/Action/GameOfficial/AssignByAssignor/AssignorForm.php
src/AppBundle/Action/GameOfficial/AssignByAssignor/AssignorView.php
src/AppBundle/Action/GameOfficial/config/services.yml
src/AppBundle/Action/Schedule2016/ScheduleTemplate.php

Need to make a tweak under Schedule2016.

Assignor form skeleton.

---

src/AppBundle/Action/Project/User/Login/UserLoginForm.php

Tabs now go: email => password => login => password reset.

Adjusted tab indexes on login form.

---

src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php

- Fixed logic on RegYear styling

172-MY_bgcolor_error

---

src/AppBundle/Resources/public/css/bs_custom.css

190-button_margin

---

src/AppBundle/Action/App/Admin/AdminView.php
src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Action/RegTeam/RegTeamUploadForm.php
src/AppBundle/Resources/public/js/cerad-file-input.js

- fixed the js to run #fileinput from the js folder
- also fixes the checkboxes which broke when moving load scripts to the top

186-update_admin_links

---

src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingSearchForm.php

- need to trap Admin/Listing/Update

102-single_quotes

---

src/AppBundle/Action/Schedule2016/ScheduleFinderTest.php

- update constructor parameters

198-fix-scheduleFinderTest

---

src/AppBundle/Action/App/Admin/AdminSwitchUserForm.php
src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorController.php
src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorSearchForm.php
src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorView.php
src/AppBundle/Action/Schedule2016/routes.yml
src/AppBundle/Action/Schedule2016/services.yml

Rebased to master commit 00831ff9be3b338e121537097c8a12ba1db4840e

185 assignor filters

---

src/AppBundle/Action/App/Admin/AdminView.php
src/AppBundle/Action/App/File/FilePdfController.php
src/AppBundle/Action/App/Home/HomeView.php
src/AppBundle/Action/App/TextAlerts/TextAlertsView.php
src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Resources/public/css/app.css

Rebased on master commit 2b7a90dc29c32316ddf0de96e1e93768d833203f

203 style textalert

---

src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalView.php

Updated view to show teams 5-8

200 add consolation bracket to final results

---

src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorController.php
src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorSearchForm.php
src/AppBundle/Action/Schedule2016/Assignor/ScheduleAssignorView.php
src/AppBundle/Action/Schedule2016/Game/ScheduleGameView.php
src/AppBundle/Action/Schedule2016/ScheduleView.php

rebased on 209-fix_selector_layout

211 assignor search stuck on defaults

---

src/AppBundle/Action/BaseTemplate.php

- Replaced RainedOut logo with menu link to /textalerts

214-update_top_menu

---

src/AppBundle/Action/Game/GameFinder.php
src/AppBundle/Action/Game/Listing/GameListingController.php
src/AppBundle/Action/Game/Listing/GameListingSearchForm.php
src/AppBundle/Action/Game/Listing/GameListingView.php

Added max game number per division to game listing page.

---

src/AppBundle/Action/Schedule2016/MedalRound/ScheduleMedalRoundController.php

- reset default projectId to NG2016

224-reset_schedule_medalround_projectID

---

src/AppBundle/Action/App/Admin/AdminView.php
src/AppBundle/Action/Game/Listing/GameListingView.php
src/AppBundle/Resources/public/css/app.css
src/AppBundle/Resources/public/css/bs_custom.css

- removed unused links on Admin page
- removed extra <hr> on GameListingView
- added some height to table rows for better readability
- enhanced the table separators color for better viewability

226-update_admin_links, etc

---

src/AppBundle/Action/Game/GameId.php
src/AppBundle/Action/Game/GameUpdater.php
src/AppBundle/Action/Game/GameUpdaterTest.php
src/AppBundle/Action/Game/Migrate/AdjustGames2016Command.php
src/AppBundle/Action/Game/Migrate/SeqGameNumbersCommand.php
src/AppBundle/Action/Game/services.yml

Provides the ability to sequence game numbers for a division.  This will eliminate any gaps that may have occurred due to schedule updates.
Not sure if we will use it for 2016 but it is there if we need it.

Game Sequence Number command

---

src/AppBundle/Action/RegTeam/RegTeamUpdater.php

232-fix_team_import

---

src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php

- handle null as 'no' explicitly to avoid blank list to "willCoach = no"

237-fix_willxxx

---

src/AppBundle/Action/Game/Migrate/notes.md
src/AppBundle/Action/GameOfficial/AssignByAssignee/AssigneeForm.php
src/AppBundle/Action/GameOfficial/GameOfficialVoter.php
src/AppBundle/Action/GameOfficial/config/services.yml
src/AppBundle/Action/RegPerson/RegPersonFinder.php
src/AppBundle/Action/Schedule2016/ScheduleTemplate.php

Referee must be approved to signup for games

---

src/AppBundle/Action/Game/GameFinder.php
src/AppBundle/Action/Game/Listing/GameListingView.php
src/AppBundle/Action/Game/RegTeam.php
src/AppBundle/Action/PoolTeam/Import/PoolTeamImportForm.php
src/AppBundle/Action/PoolTeam/Import/PoolTeamImportReaderExcel.php
src/AppBundle/Action/PoolTeam/Import/PoolTeamImportUpdater.php
src/AppBundle/Action/PoolTeam/Import/PoolTeamImportView.php
src/AppBundle/Action/RegTeam/Export/RegTeamExportController.php
src/AppBundle/Action/RegTeam/Export/RegTeamExportViewExcel.php
src/AppBundle/Action/RegTeam/Export/RegTeamExportWriterExcel.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportController.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportForm.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportReaderExcel.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportResults.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportUpdater.php
src/AppBundle/Action/RegTeam/Import/RegTeamImportView.php
src/AppBundle/Action/RegTeam/RegTeamFinder.php
src/AppBundle/Action/RegTeam/config/routes.yml
src/AppBundle/Action/RegTeam/config/services.yml

Refactored the reg team import/export functionality.  Mostly to make it work the way I am used to.  Was a bit confused about some of the existing code.
New routes /import2 and /export2 use the new functionality.
The old functionality was not changed and can still be accessed via /import and /export

Reg teams import/export

---

src/AppBundle/Resources/public/css/app.css

242-table_borders

---

src/AppBundle/Action/Game/Migrate/ValidateGamesCommand.php
src/AppBundle/Action/Game/services.yml

Currently check for Open assignments that still have a registered person attached.

Simple game database validator

---

app/config/parameters.yml.dist
src/AppBundle/Action/AbstractForm.php
src/AppBundle/Action/App/services.yml
src/AppBundle/Action/BaseTemplate.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalSearchForm.php
src/AppBundle/Action/Results2016/FinalStandings/ResultsFinalView.php
src/AppBundle/Action/Results2016/MedalRound/ResultsMedalRoundSearchForm.php
src/AppBundle/Action/Results2016/MedalRound/ResultsMedalRoundView.php
src/AppBundle/Action/Results2016/PoolPlay/ResultsPoolPlaySearchForm.php
src/AppBundle/Action/Results2016/Sportsmanship/ResultsSportsmanshipSearchForm.php

Also hides final results menu item until after last game results are posted.
Updates parameters.yml.dist.  Please review before merging.  You may have another way of doing this.

246 hide program selector on results views

---

app/config/projects/AYSONationalGames2016.yml

update assignor info and switch to Tom B' mobile number

update contact information

---

src/AppBundle/Resources/public/css/common.css

Remove references to /css/bebasneue.eot or  /css/pala.eot

---

src/AppBundle/Action/Game/Migrate/AdjustGames2016Command.php

Adjust soccerfest game duration.

---

src/AppBundle/Action/Schedule2016/My/ScheduleMyController.php
src/AppBundle/Action/Schedule2016/ScheduleFinder.php

Fixes #261
Also added some sort by constants to ScheduleGameFinder.

Properly sorts my schedule.

---

src/AppBundle/Action/RegPerson/Persons/Update/PersonsUpdateView.php

- Update "Notes on Adding a Team" to be "Notes on Adding a Person to your Crew"

263-Notes_title

---

src/AppBundle/Action/App/Welcome/WelcomeView.php

- reset url on welcome page to user/password/reset-request

265-Bad_link

---

src/AppBundle/Action/App/Admin/AdminView.php

- switched to reg_team_import2 & reg_team_export2

266-update_team_mgmt_links

---

src/AppBundle/Action/Project/Person/Admin/Listing/AdminListingViewFile.php
src/AppBundle/Action/Project/Person/ProjectPerson.php

- added createdOn timestamp to exported report
- updatedOn is not being updated so did not include this

272-add-times-to-people-report

---

src/AppBundle/Action/Project/Person/Admin/Update/AdminUpdateForm.php

- fixed the data update
- made checkbox available based on volunteer's plans

277-approved_to_volunteer

---

src/AppBundle/Action/Schedule2016/ScheduleTemplate.php

something we added in 2014; helpful in reviewing self-assignments

280-style_section_conflicts

---

src/AppBundle/Action/GameOfficial/AssignByAssignor/AssignorController.php

Guess it was never used on 2014.
Fixes #276 #279

Properly handle Rejected.

---

src/AppBundle/Action/Schedule2016/MedalRound/ScheduleMedalRoundCalculator.php

Updated MedalRoundCalculator to 2016 poolKeys

---

app/config/security.yml
src/AppBundle/Action/GameReport2016/Update/GameReportUpdateForm.php
src/AppBundle/Action/GameReport2016/routes.yml

- fixed typo in security.yml
- move GameStatus & Report Status above button group

reorder_scorer_view: to improve workflow for verification
